# Generated by Django 5.2.6 on 2025-09-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip', models.URLField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('CPU', 'CPU'), ('MEMORY', 'Memory'), ('DISK', 'Disk')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolve_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='metric.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.PositiveIntegerField()),
                ('memory', models.PositiveIntegerField()),
                ('disk', models.PositiveIntegerField()),
                ('uptime', models.CharField(max_length=50)),
                ('timestap', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metric.machine')),
            ],
            options={
                'ordering': ['-timestap'],
            },
        ),
    ]
