# Generated by Django 5.2.6 on 2025-09-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
