# Generated by Django 5.2.6 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0002_alter_metric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
