# Generated by Django 5.2.6 on 2025-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0003_alter_metric_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
